### PR TITLE
Reduce image size

### LINKED ISSUE #75: Reduce image size
Currently the image is 2GB. As mentioned on the [forum](http://forum.exercism.org/t/docker-image-sizes/6478/12) a first step might be to remove the stable toolchain, which is over 500MB.

As suggested [here](http://forum.exercism.org/t/docker-image-sizes/6478/13), another impactful step might be to reduce the list of supported crates in the local registry to ones actually useful to the exercises.

### PR DESCRIPTION
**Pull request by senekor**
closes #75

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
How much do we save with this?

**Comment by senekor** [comment]
A bit more than 50% or 1GB, old size was 2GB plus change, new size is ~950MB.

**Comment by senekor** [comment]
95O is with alpine, I switched to debian though to see if CI is fixed

**Comment by senekor** [comment]
debian is 1.6GB but it passes CI, while alpine does not. debian-slim is 970MB, which is almost the same as alpine, let's see if it passes CI.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
