### PR TITLE
Add unicode-reverse

### PR DESCRIPTION
**Pull request by senekor**
I may have removed this crate in one of my past purges. It had received its last update 5 years ago. But it got a new version recently, mainly updating the Rust editions. So the crate isn't abandoned, it's just "done".

It's also decently popular and shows up quite high on crates.io when searching for "reverse" or "grapheme".

### CODE REVIEW

**Comment by senekor** [comment]
[related forum post](https://forum.exercism.org/t/reversing-strings-external-crates/12450/4)

**Review by ErikSchierboom — APPROVED** [review]

**Comment by senekor** [comment]
@ptufts This is a little quirk of Rust package management. Rust identifiers do not allow a dash, so `unicode-reverse` is not a valid identifier in the language. However, cargo and crates.io DO allow dashes in crate names. These dashes are then mapped to underscores in the Rust source code. Here is the [crates.io page for `uncode-reverse`](https://crates.io/crates/unicode-reverse) (with a dash). You can use it in Rust source code with `use unicode_reverse`.

**Comment by ptufts** [comment]
Ah, I see what you mean, but also see the first half of my comment: unicode_reverse (underscore) also appears to fail, unless I'm invoking it incorrectly:

`unresolved import unicode_reverse--> src/lib.rs:1:5 | 1 | use unicode_reverse; |     ^^^^^^^^^^^^^^^ no external crate unicode_reverse `

**Comment by senekor** [comment]
Have you added it to your `Cargo.tom`?

```toml
[dependencies]
unicode-reverse = "*"
```

**Pull request merged**
