### PR TITLE
Update to Rust 1.70

### PR DESCRIPTION
**Pull request by remlse**

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
Am I correct in assuming that this is backwards compatible?

**Comment by remlse** [comment]
@ErikSchierboom 

Yeah, it's backwards compatible.

It looks like the human readable test output has become a non-deterministic again. At least on nightly. I have an idea for a fix, but I'll work on it a little later.

**Comment by remlse** [comment]
Alright, that should fix it. Sorry for the delay, the due date for my bachelor thesis was on Friday :smiley: @ErikSchierboom

**Review by ErikSchierboom — APPROVED** [review]
Good use of comments!

**Pull request merged**
