### PR TITLE
Fix bloated docker image

### PR DESCRIPTION
**Pull request by senekor**

### CODE REVIEW

**Comment by senekor** [comment]
By coincidence, I inspected the size of the docker image when merging the prune-dependencies branch. It was 2.5 GB. Turns out `local-registry/target` was acciedentally copied into the final image. Removing that puts us back to around 890 MB.

I don't know when and why this regression was introduced. It seems that `.dockerignore` has slightly different sematics than `.gitignore`, because for the latter `target/` also automatically matches subdirectories.

**Review by ErikSchierboom — APPROVED** [review]
Great work! Would this also apply to the other Rust docker images?

**Comment by senekor** [comment]
I think they should be fine, their docker build is quite a bit simpler. I'll check the representer and the analyzer anyway in the next couple days.

**Comment by senekor** [comment]
@ErikSchierboom the analyzer and representer images are only 16 and 17 MB :+1:

**Pull request merged**
